/**
 * Sahajanand APC Admin Service
 * Centralized logic for data persistence, report generation, and government compliance.
 */

class DataService {
    constructor() {
        this.STORAGE_KEYS = {
            STAFF: 'baps_staff',
            STUDENTS: 'baps_students',
            INVENTORY: 'baps_inventory',
            GATEPASS: 'baps_gatepass',
            VISITORS: 'baps_visitors',
            GOVT_REQUESTS: 'baps_govt_requests',
            MEDICAL_LOGS: 'baps_medical',
            LIBRARY: 'baps_library',
            ALUMNI: 'baps_alumni',
            EXAMS: 'baps_exams'
        };
    }

    _get(key) {
        return JSON.parse(localStorage.getItem(key) || '[]');
    }

    _set(key, data) {
        localStorage.setItem(key, JSON.stringify(data));
    }

    // Generic Add
    addRecord(type, record) {
        const key = this.STORAGE_KEYS[type.toUpperCase()];
        if (!key) throw new Error(`Unknown data type: ${type}`);

        const data = this._get(key);
        record.id = record.id || Date.now().toString(36) + Math.random().toString(36).substr(2);
        record.timestamp = new Date().toISOString();
        data.push(record);
        this._set(key, data);
        return record;
    }

    // Generic Get All
    getAll(type) {
        const key = this.STORAGE_KEYS[type.toUpperCase()];
        return this._get(key);
    }
}

class ReportService {
    constructor(dataService) {
        this.dataService = dataService;
    }

    generateHTMLReport(title, subtitle, columns, data) {
        const date = new Date().toLocaleDateString();
        const rows = data.map(item => {
            return `<tr>${columns.map(col => `<td>${item[col.field] || '-'}</td>`).join('')}</tr>`;
        }).join('');

        return `
            <html>
            <head>
                <title>${title} - Sahajanand APC</title>
                <style>
                    body { font-family: 'Times New Roman', serif; padding: 40px; }
                    .header { text-align: center; border-bottom: 2px solid #000; padding-bottom: 20px; margin-bottom: 30px; }
                    .logo { font-size: 24px; font-weight: bold; color: #d35400; text-transform: uppercase; }
                    h1 { margin: 10px 0 5px; font-size: 20px; }
                    .meta { display: flex; justify-content: space-between; margin-bottom: 20px; font-size: 14px; }
                    table { width: 100%; border-collapse: collapse; margin-top: 20px; font-size: 12px; }
                    th, td { border: 1px solid #333; padding: 8px; text-align: left; }
                    th { background-color: #f0f0f0; }
                    .footer { margin-top: 50px; text-align: center; font-size: 10px; border-top: 1px solid #ccc; padding-top: 10px; }
                </style>
            </head>
            <body>
                <div class="header">
                    <div class="logo">Sahajanand APC</div>
                    <h1>${title}</h1>
                    <p>${subtitle}</p>
                </div>
                <div class="meta">
                    <span><strong>Date:</strong> ${date}</span>
                    <span><strong>Generated By:</strong> Admin System</span>
                </div>
                <table>
                    <thead>
                        <tr>${columns.map(c => `<th>${c.header}</th>`).join('')}</tr>
                    </thead>
                    <tbody>${rows}</tbody>
                </table>
                <div class="footer">
                    <p>This is a computer-generated document. No signature is required.</p>
                    <p>Sahajanand APC Management System | Official Record</p>
                </div>
                <script>window.print();</script>
            </body>
            </html>
        `;
    }

    openReport(title, subtitle, columns, dataSourceKey) {
        const data = this.dataService.getAll(dataSourceKey);
        // Fallback for demo if empty
        if (data.length === 0) {
            alert("No data found to generate report. Please add records first.");
            return;
        }

        const html = this.generateHTMLReport(title, subtitle, columns, data);
        const win = window.open('', '_blank');
        win.document.write(html);
        win.document.close();
    }
}

// Global Instance
window.BapsAdmin = new class {
    constructor() {
        this.data = new DataService();
        this.reports = new ReportService(this.data);
    }

    // Quick Helpers for Buttons
    saveGovtRequest(form) {
        const formData = new FormData(form);
        const record = Object.fromEntries(formData.entries());
        record.status = 'Pending';
        this.data.addRecord('GOVT_REQUESTS', record);
        alert('Government Request Submitted Successfully!');
        return false; // Prevent reload if used in onsubmit
    }

    generateAndDownloadRequest(form) {
        const formData = new FormData(form);
        const data = Object.fromEntries(formData.entries());
        const date = new Date().toLocaleDateString();

        // Save to audit log anyway
        const record = { ...data };
        record.status = 'Generated';
        this.data.addRecord('GOVT_REQUESTS', record);

        // Professional Letter Template
        const content = `
            <!DOCTYPE html>
            <html>
            <head>
                <title>${data.title} - Formal Request</title>
                <style>
                    body { font-family: 'Times New Roman', serif; line-height: 1.6; color: #333; max-width: 800px; margin: 0 auto; padding: 40px; }
                    .header { text-align: center; margin-bottom: 40px; border-bottom: 2px solid #b71c1c; padding-bottom: 20px; }
                    .logo-text { font-size: 28px; font-weight: bold; color: #b71c1c; text-transform: uppercase; letter-spacing: 1px; }
                    .sub-logo { font-size: 14px; color: #555; margin-top: 5px; }
                    .date { text-align: right; margin-bottom: 40px; }
                    .recipient { margin-bottom: 30px; font-weight: bold; }
                    .subject { font-weight: bold; text-decoration: underline; margin-bottom: 30px; }
                    .body-content { text-align: justify; margin-bottom: 60px; min-height: 300px; white-space: pre-wrap; }
                    .signature-block { margin-top: 60px; }
                    .name { font-weight: bold; }
                    .contact { font-size: 14px; color: #555; }
                    .footer { margin-top: 80px; text-align: center; border-top: 1px solid #ddd; padding-top: 10px; font-size: 12px; color: #888; }
                    @media print { body { padding: 0; } }
                </style>
            </head>
            <body>
                <div class="header">
                    <div class="logo-text">Sahajanand APC</div>
                    <div class="sub-logo">Vallabh Vidyanagar | Managed by BAPS Swaminarayan Sanstha</div>
                </div>

                <div class="date">
                    <strong>Date:</strong> ${date}
                </div>

                <div class="recipient">
                    To,<br>
                    The Competent Authority,<br>
                    ${data.department}<br>
                    Gujarat, India.
                </div>

                <div class="subject">
                    Subject: ${data.title}
                </div>

                <div class="body-content">
                    Respected Sir/Madam,

                    ${data.details}

                    We request you to kindly process this application at your earliest convenience. We are ready to provide any further documents or clarifications if required.

                    Thanking You,
                    Yours Sincerely,
                </div>

                <div class="signature-block">
                    <div class="name">${data.rep_name}</div>
                    <div>Authorized Signatory</div>
                    <div class="contact">Contact: ${data.rep_contact}</div>
                    <div class="contact">Sahajanand APC</div>
                </div>

                <div class="footer">
                    This document is officially generated by the Sahajanand APC Management Portal.<br>
                    Address: BAPS Swaminarayan Mandir, N.H. No. 8, Vallabh Vidyanagar - 388120.
                </div>
            </body>
            </html>
        `;

        // Create Blob and Download
        const blob = new Blob([content], { type: 'text/html' });
        const url = window.URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url;
        a.download = `Request_${data.title.replace(/[^a-z0-9]/gi, '_').toLowerCase()}_${Date.now()}.html`;
        document.body.appendChild(a);
        a.click();

        // Cleanup
        window.URL.revokeObjectURL(url);
        document.body.removeChild(a);

        alert('Document Generated & Downloaded Successfully!');
    }

    generateAssetReport() {
        this.reports.openReport(
            'Infrastructure & Asset Audit',
            'Submission for Education Department (Physical Verification)',
            [{ header: 'Item Name', field: 'item' }, { header: 'Category', field: 'category' }, { header: 'Qty', field: 'quantity' }, { header: 'Vendor', field: 'supplier' }],
            'INVENTORY'
        );
    }

    generateStudentReport() {
        // Mocking student data if not present in this specific localStorage key yet
        // In a real app, this would pull from the students key
        this.reports.openReport(
            'Student Enrollment Registry',
            'Submission for Home Ministry (Occupancy Check)',
            [{ header: 'GR No', field: 'id' }, { header: 'Name', field: 'name' }, { header: 'Course', field: 'course' }],
            'STUDENTS' // Ensure this is populated or handle empty
        );
    }

    // --- GATEPASS DOCUMENT GENERATION ---
    generateGatepassDocument(passData) {
        // SVG Signatures
        const sigAdmin = `<svg width="200" height="60" viewBox="0 0 200 60" xmlns="http://www.w3.org/2000/svg"><style>.sig{font-family:'Brush Script MT', cursive; font-size:24px; fill:#000080;}</style><text x="10" y="40" class="sig">Prof. Dr. Bhavikkumar Patel</text><line x1="10" y1="50" x2="190" y2="50" stroke="#000080" stroke-width="2"/></svg>`;

        const sigKothari = `<svg width="200" height="60" viewBox="0 0 200 60" xmlns="http://www.w3.org/2000/svg"><style>.sig2{font-family:'Snell Roundhand', cursive; font-size:20px; fill:#b71c1c;}</style><text x="10" y="40" class="sig2">Dr. Sadhu Adbhutanand Das</text><path d="M10 50 Q 50 45, 90 50 T 180 50" stroke="#b71c1c" fill="none"/></svg>`;

        const sigBlock = `<svg width="200" height="60" viewBox="0 0 200 60" xmlns="http://www.w3.org/2000/svg"><style>.sig3{font-family:'Zapfino', cursive; font-size:18px; fill:#2e7d32;}</style><text x="10" y="40" class="sig3">Sadhu Rasikvihari Das</text><line x1="10" y1="50" x2="150" y2="50" stroke="#2e7d32" stroke-width="1" stroke-dasharray="4"/></svg>`;

        // Content Styling based on Type
        const isEmergency = passData.type === 'Emergency';
        const themeColor = isEmergency ? '#d32f2f' : '#b71c1c'; // Red vs Dark Red/Blue default
        const titleText = isEmergency ? 'EMERGENCY MOVEMENT AUTHORIZATION' : 'Student Movement Authorization';
        const stampText = isEmergency ? 'EMERGENCY APPROVED<br>URGENT ACTION' : 'OFFICIALLY APPROVED<br>ISSUED BY ADMIN OFFICE<br>(PHYSICAL COPY)';
        const borderColor = isEmergency ? '#d32f2f' : '#333';

        const html = `
            <!DOCTYPE html>
            <html>
            <head>
                <title>Official Gatepass - ${passData.id}</title>
                <style>
                    body { font-family: 'Times New Roman', serif; padding: 40px; max-width: 900px; margin: 0 auto; border: 5px double ${borderColor}; }
                    .header { text-align: center; border-bottom: 2px solid ${borderColor}; padding-bottom: 20px; margin-bottom: 30px; }
                    .title { font-size: 28px; font-weight: bold; text-transform: uppercase; letter-spacing: 2px; color: ${themeColor}; }
                    .meta-table { width: 100%; border-collapse: collapse; margin-bottom: 30px; }
                    .meta-table td { padding: 8px; border: 1px solid #ccc; font-size: 14px; }
                    .meta-table strong { color: #333; }
                    .terms { font-size: 11px; text-align: justify; columns: 2; column-gap: 40px; margin-bottom: 40px; border-top: 1px solid #eee; padding-top: 20px; }
                    .signatures { display: flex; justify-content: space-between; margin-top: 50px; text-align: center; }
                    .sig-box { width: 30%; }
                    .sig-img { border-bottom: 1px solid #999; margin-bottom: 5px; padding-bottom: 5px; }
                    .stamp { position: absolute; top: 60px; right: 60px; border: 3px solid ${themeColor}; color: ${themeColor}; padding: 10px; font-weight: bold; transform: rotate(-15deg); opacity: 0.8; font-size: 20px; text-transform: uppercase; }
                </style>
            </head>
            <body>
                <div class="stamp">${stampText}<br>${new Date().toLocaleDateString()}</div>
                
                <div class="header">
                    <div style="font-size: 16px; font-weight: bold;">SAHAJANAND APC, VALLABH VIDYANAGAR</div>
                    <div style="font-size: 12px;">Pramukh Swami Maharaj Marg, Near Sardar Patel University, Anand - 388120</div>
                    <br>
                    <div class="title">${titleText}</div>
                    <div style="font-size: 14px;">Gatepass Reference ID: <strong>${passData.id}</strong> <span style="color:red; font-weight:bold;">${isEmergency ? '(URGENT)' : ''}</span></div>
                </div>

                <table class="meta-table">
                    <tr>
                        <td width="20%"><strong>Student Name</strong></td>
                        <td width="30%">${passData.student}</td>
                        <td width="20%"><strong>GR Number</strong></td>
                        <td width="30%">${passData.grNo || '20240000'}</td>
                    </tr>
                    <tr>
                        <td><strong>Room Number</strong></td>
                        <td>${passData.room || 'B-304'}</td>
                        <td><strong>Course/Branch</strong></td>
                        <td>B.E. (Computer) - Sem 6</td>
                    </tr>
                    <tr>
                        <td><strong>Destination</strong></td>
                        <td colspan="3" style="font-size: 16px; font-weight: bold;">${passData.destination}</td>
                    </tr>
                    <tr>
                        <td><strong>Reason for Leave</strong></td>
                        <td colspan="3">${passData.reason}</td>
                    </tr>
                    <tr>
                        <td><strong>Date/Time OUT</strong></td>
                        <td>${passData.dateOut}</td>
                        <td><strong>Date/Time IN (Expected)</strong></td>
                        <td>${passData.dateIn}</td>
                    </tr>
                    <tr>
                        <td><strong>Transport Mode</strong></td>
                        <td>Personal Vehicle / Public Bus</td>
                        <td><strong>Accompanied By</strong></td>
                        <td>Self / Guardians</td>
                    </tr>
                    <tr>
                        <td><strong>Student Contact</strong></td>
                        <td>+91 98765 43210</td>
                        <td><strong>Parent Contact</strong></td>
                        <td>+91 99887 76655</td>
                    </tr>
                </table>

                <div class="terms">
                    <strong>TERMS AND CONDITIONS FOR HOSTEL RESIDENTS:</strong><br><br>
                    1. <strong>Authorization:</strong> This gatepass is valid only for the student mentioned above. It is non-transferable. The student must carry their valid Hostel ID card along with this pass at all times during the journey.<br>
                    2. <strong>Timings:</strong> The student is strictly required to return to the hostel premises by the "Date/Time IN" mentioned above. Late reporting without prior intimation to the Rector will attract disciplinary action as per the BAPS Chhatralay Code of Conduct (Clause 4.2).<br>
                    3. <strong>Safety & Responsibility:</strong> The hostel administration is not responsible for any mishap, accident, or loss of personal belongings during the travel period. The student travels at their own risk and responsibility.<br>
                    4. <strong>Prohibited Activities:</strong> During the leave period, the student must maintain the dignity and values of BAPS. Engaging in political rallies, immoral activities, or visiting prohibited areas is strictly forbidden.<br>
                    5. <strong>Medical Emergency:</strong> In case of a medical emergency during the leave, the student or their guardian must immediately inform the Block Superintendent or the Kothari Swami.<br>
                    6. <strong>Extension of Leave:</strong> No extension of leave will be granted telephonically except in extreme emergencies. The student must return and re-apply for any further leave.<br>
                    7. <strong>Verification:</strong> This document is subject to verification by security personnel at the main gate. Any manipulation of data in this digital document is a punishable offense.<br>
                    8. <strong>Parental Consent:</strong> It is presumed that the student has obtained necessary permissions from parents/guardians before applying for this gatepass. Random checks may be conducted by the administration to verify parental consent.<br>
                    9. <strong>Hostel Property:</strong> The student must ensure that their room is locked and no electrical appliances are left on before leaving the hostel premises.<br>
                    10. <strong>Surrender:</strong> This pass must be surrendered to the Security Office upon return. Failure to do so will mark the student as "Absent" in the nightly headcount.
                    <br><br>
                    <em>"Discipline is the bridge between goals and accomplishment." - HH Pramukh Swami Maharaj</em>
                </div>

                <div class="signatures">
                    <div class="sig-box">
                        <div class="sig-img">${sigAdmin}</div>
                        <strong>Prof. Dr. Bhavikkumar Patel</strong><br>
                        <small>Administrator</small>
                    </div>
                    <div class="sig-box">
                        <div class="sig-img">${sigBlock}</div>
                        <strong>Sadhu Rasikvihari Das</strong><br>
                        <small>Block Head (Block 3)</small>
                    </div>
                    <div class="sig-box">
                        <div class="sig-img">${sigKothari}</div>
                        <strong>Dr. Sadhu Adbhutanand Das</strong><br>
                        <small>Kothari Swami</small>
                    </div>
                </div>

                <div style="text-align: center; margin-top: 20px; font-size: 10px; color: #666;">
                    System Generated Stamp: ${Date.now()}-${Math.floor(Math.random() * 1000)} | IP: 192.168.1.42 | Verified by Biometric Server | <strong>OFFICIAL PHYSICAL COPY - ADMIN OFFICE</strong>
                </div>
            </body>
            </html>
        `;

        // Download logic
        const blob = new Blob([html], { type: 'text/html' });
        const url = window.URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url;
        a.download = `Gatepass_${passData.student}_${Date.now()}.html`;
        document.body.appendChild(a);
        a.click();
        window.URL.revokeObjectURL(url);
        document.body.removeChild(a);
    }

    // --- FEE RECEIPT GENERATION ---
    generatePaymentReceipt(data) {
        const html = `
            <!DOCTYPE html>
            <html>
            <head>
                <title>Receipt - ${data.txnId}</title>
                <style>
                    body { font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; padding: 40px; background: #fff; max-width: 600px; margin: 0 auto; border: 2px solid #2E7D32; border-radius: 10px; }
                    .header { text-align: center; border-bottom: 2px dashed #2E7D32; padding-bottom: 15px; margin-bottom: 20px; }
                    .logo { color: #2E7D32; font-size: 22px; font-weight: 800; text-transform: uppercase; }
                    .success-icon { font-size: 40px; color: #2E7D32; margin-bottom: 10px; }
                    .details { font-size: 14px; line-height: 1.8; color: #333; }
                    .amount-box { background: #E8F5E9; color: #2E7D32; padding: 15px; text-align: center; font-size: 24px; font-weight: bold; border-radius: 8px; margin: 20px 0; }
                    .footer { text-align: center; font-size: 11px; color: #666; margin-top: 30px; border-top: 1px solid #eee; padding-top: 10px; }
                    .stamp { position: absolute; transform: rotate(-20deg); top: 150px; right: 80px; border: 3px double #2E7D32; color: #2E7D32; font-weight: bold; padding: 10px; font-size: 18px; opacity: 0.2; }
                </style>
            </head>
            <body>
                <div class="header">
                    <div class="success-icon">✔</div>
                    <div class="logo">Payment Successful</div>
                    <div style="font-size: 12px; color: #666;">BAPS Swaminarayan Chhatralay</div>
                </div>

                <div class="stamp">PAID & VERIFIED</div>

                <div class="details">
                    This certifies that <strong>${data.student}</strong> has successfully paid the fee amount via <strong>${data.method}</strong>.<br><br>
                    
                    <strong>Transaction ID:</strong> ${data.txnId}<br>
                    <strong>Date:</strong> ${data.date}<br>
                    <strong>Purpose:</strong> Hostel/Mess Fees
                </div>

                <div class="amount-box">
                    ₹ ${data.amount}
                </div>

                <div style="font-size: 12px; text-align: justify; color: #555;">
                    This receipt is electronically generated and valid for all official BAPS APC records. The payment has been credited to the institute's account. For any discrepancies, please contact the accounts office within 3 days.
                </div>

                <div class="footer">
                    Authorized by Accounts Dept | BAPS APC Vallabh Vidyanagar<br>
                    <em>Jai Swaminarayan</em>
                </div>
            </body>
            </html>
        `;

        const blob = new Blob([html], { type: 'text/html' });
        const url = window.URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url;
        a.download = `Receipt_${data.txnId}.html`;
        document.body.appendChild(a);
        a.click();
        window.URL.revokeObjectURL(url);
        document.body.removeChild(a);
    }
}
